name: Publish (gh-pages branch)

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Generate resume JSON
        run: |
          python parse_resume.py
      - name: Prepare site
        run: |
          rm -rf dist
          mkdir dist
          cp -R site/* dist/
          cp resume/parsed_resume.json dist/ || true
          cp resume/json_resume.json dist/ || true
          # Remove custom domain if not configured to avoid redirect
          rm -f dist/CNAME
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          force_orphan: true
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: "chore: publish site to gh-pages"
